services:
  comparator-ktor:
    build:
      context: .
      dockerfile: comparator-app-ktor/Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped

  comparator-websocket:
    build:
      context: .
      dockerfile: comparator-app-websocket/Dockerfile
    ports:
      - "8081:8081"
    restart: unless-stopped